### ISSUE TITLE
End2End Test

### ISSUE THREAD

**Issue by Second222None** [LMCache/LMCache#231]
**Describe the bug**

Since there is no powerful GPU, we have to run the End2End test with a samll model `Qwen/Qwen2-1.5B`. LMcache could start successfully. We get the error when sending requests to server. 

The error from current screen:
![image](https://github.com/user-attachments/assets/44f79f54-edd1-4a45-9600-f0b62abab70c)

And the error from `/tmp/root-8000-stdout.log
`
```
(VllmWorkerProcess pid=73509) ERROR 11-20 22:14:12 multiproc_worker_utils.py:233]     _, _, num_heads, head_size = kv_cache[0].shape
(VllmWorkerProcess pid=73509) ERROR 11-20 22:14:12 multiproc_worker_utils.py:233] ValueError: not enough values to unpack (expected 4, got 2) 
```

env:
- OS: Ubuntu 22.04.5 LTS
- vllm: v0.6.2 (pip install vllm==0.6.2)
- LMcache: v0.1.3-alpha (installed from source)
- lmcache-vllm: v0.6.2.2 (installed from source)
- GPU: Tesla T4 (16GB) x 2

**To Reproduce**
1. Set to use `Qwen/Qwen2-1.5B` by changing `tests/tests.py`.  `def test_lmcache_local_cpu(model = "Qwen/Qwen2-1.5B") -> pd.DataFrame:`
2. python3 main.py tests/tests.py -f test_lmcache_local_cpu -o outputs/

**Expected behavior**
Get the performance number and generate the figure.

**Comment by YaoJiayi** [comment]
Yes, thanks for pinting this out! We are aware of this issue (some Tesla GPUs are not supported). Someone is working on this.

**Comment by Second222None** [comment]
Can you give some further hints or a temperary/quick fix to workaround it? We have no more powerful GPUs, we'd like to have a taste for LMCache. Thanks.

**Comment by ApostaC** [comment]
Hey @Second222None , here's the code caused the problem: https://github.com/LMCache/lmcache-vllm/blob/5b964d6fc9c40627e45c849dd51aeabafba3c04a/lmcache_vllm/vllm_adapter.py#L453 
The reason is, when using GPUs with older architecture (like Turing and Tesla), vLLM will have a different shape of `kvcaches` tensor (the paged KV buffer). So you may need to make some changes there. 

Btw, we will be more than happy to hear how you have fixed that problem, and PRs are welcomed.
